# Generated by Django 3.1.7 on 2021-03-02 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import scheduler.rest_requests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(blank=True, max_length=30, verbose_name='Request Name')),
                ('url', scheduler.rest_requests.models.HTTPSURLField(default='https://', help_text='Request URL, https:// only')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('HEAD', 'HEAD'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('PATCH', 'PATCH')], default='GET', max_length=8, verbose_name='Method')),
                ('headers', models.JSONField(blank=True, default=dict, null=True, verbose_name='Request Headers')),
                ('body', models.JSONField(blank=True, default=dict, null=True, verbose_name='Request Body')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rest request',
                'verbose_name_plural': 'Rest requests',
            },
        ),
        migrations.CreateModel(
            name='RequestSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date_time', models.DateTimeField(default=scheduler.rest_requests.models.get_default_schedule_datetime, verbose_name='Scheduled Date Time')),
                ('status', models.IntegerField(choices=[(0, 'Not scheduled'), (1, 'Pending'), (2, 'Processing'), (3, 'Processed'), (4, 'Failed'), (5, 'Cancelled')], default=0, verbose_name='Status')),
                ('task_id', models.CharField(blank=True, max_length=256)),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Rest response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('rest_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_requests.restrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request schedule',
                'verbose_name_plural': 'Request schedules',
            },
        ),
    ]
