# Generated by Django 3.1.7 on 2021-03-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestschedule',
            name='retry',
            field=models.IntegerField(default=0, verbose_name='Retry'),
        ),
    ]
